### PR TITLE
Unistore example for React

### PR DESCRIPTION
**Pull request by juandc**
Solves #24

### CODE REVIEW

**Comment by GantMan** [comment]
@juandc - I need to give you a special mention in the blog post for all these conversions!  Very cool!

**Comment by GantMan** [comment]
@juandc - Here I did it to your `react-easy-state` example.   It makes the resulting code very small and very clean so it's focussed on state differences.

https://github.com/GantMan/ReactStateMuseum/pull/33/files

**Comment by juandc** [comment]
Working on! :muscle:

**Comment by juandc** [comment]
Its done :smile:

**Comment by GantMan** [comment]
Graet work @juandc

**Pull request merged**
